options:
  collate: utf8_unicode_ci
  charset: utf8

Groupe:
  tableName: zcov2_groupes
  columns:
    groupe_id:             { type: integer(1), primary: true, autoincrement: true, name: groupe_id as id }
    groupe_nom:            { type: string(32), name: groupe_nom as nom }
    groupe_logo:           { type: string(255), name: groupe_logo as logo }
    groupe_logo_feminin:   { type: string(255), name: groupe_logo_feminin as logo_feminin }
    groupe_class:          { type: string(255), name: groupe_class as class }
    groupe_sanction:       { type: boolean, name: groupe_sanction as sanction }
    groupe_team:           { type: boolean, name: groupe_team as team }
    groupe_secondaire:     { type: boolean, name: groupe_secondaire as secondary }
    groupe_code:           { type: string(50), name: groupe_code as code }