imports:
    - { resource: parameters.yml }

framework:
    default_locale:  fr
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    translator:      { fallback: fr }
    session:
        storage_id: session.storage.php_bridge
    templating:
        engines:       ['php', 'twig']
        form:
            resources: 
                - 'ZcoCoreBundle:Form'

zco_vitesse:
    combine_assets: true
    assets:
        - name: google-jsapi
          type: js
          inputs: 'https://www.google.com/jsapi'
        - name: google-maps
          type: js
          inputs: 'http://maps.google.com/maps?file=api&amp;v=2&amp;key=%gmaps_api_key%'

knp_gaufrette:
    adapters:
        uploads:
            local:   { directory:  %kernel.root_dir%/../web/uploads, create: true }
    filesystems:
            uploads: { adapter: uploads }

knp_paginator:
    template:
        pagination: ZcoCoreBundle:Pagination:sliding.html.php

bazinga_geocoder:
    providers:
        google_maps:
            locale:     fr_FR