imports:
  - { resource: config.yml }

framework:
  router:    { resource: '%kernel.root_dir%/config/routing_dev.yml' }
  profiler:  { only_exceptions: false }

web_profiler:
  toolbar: '%kernel.debug%'
  intercept_redirects: '%kernel.debug%'

swiftmailer:
  disable_delivery: true

monolog:
  handlers:
    main:
      type:  stream
      path:  'php://stderr'
      level: info