imports:
  - { resource: config.yml }

framework:
    router:      { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:    { only_exceptions: false }

web_profiler:
    toolbar: %kernel.debug%
    intercept_redirects: %kernel.debug%

monolog:
    handlers:
        main:
            type:  stream
            path:  "php://stdout"
            level: debug
        firephp:
            type:  firephp
            level: info

services:
  Zco\Bundle\CoreBundle\Filesystem\UrlResolver:
    class: Zco\Bundle\CoreBundle\Filesystem\LocalUrlResolver
    arguments: [uploads]