imports:
  - { resource: parameters.yml }

framework:
  default_locale:  fr
  secret:      '%secret%'
  router:      { resource: "%kernel.root_dir%/config/routing.yml" }
  form:        true
  csrf_protection: true
  translator:    { fallback: fr }
  session:
    storage_id: session.storage.php_bridge
    handler_id: session.handler.native_file
  templating:
    engines:     ['php', 'twig']
    form:
      resources: 
        - 'ZcoCoreBundle:Form'

swiftmailer:
  transport:  swiftmailer.transport.sendgrid
  spool:      { type: memory }

zco_core:
  sendgrid:
    api_key: '%sendgrid_apikey%'
  vitesse:
    combine_assets: true

knp_gaufrette:
  adapters:
    uploads:
      local:   { directory: '%kernel.root_dir%/../web/uploads', create: true }
  filesystems:
      uploads: { adapter: uploads }

knp_paginator:
  template:
    pagination: ZcoCoreBundle:Pagination:sliding.html.php

bazinga_geocoder:
  providers:
    google_maps:
      locale:   fr_FR