parameters:
    database.host:        localhost
    database.base:        zco
    database.username:    root
    database.password:    ''

    secret: dDj85Â§fd+dedS9-sE4
    cache_default_lifetime: 600
    gmaps_api_key:  ''
    analytics_account: ''
    analytics_domain: 'zcorrecteurs.fr'
    twitter_api_key: ''
    twitter_api_secret: ''

swiftmailer:
    transport: smtp
    #username:
    #password:
    #host: localhost
    #port: 587
    #encryption: tls
    #auth_mode: plain

