zco_admin:
  resource: "@ZcoAdminBundle/Resources/config/routing.yml"

zco_content:
  resource: "@ZcoContentBundle/Resources/config/routing.yml"

zco_quote:
  resource: "@ZcoCitationsBundle/Resources/config/routing.yml"

zco_file:
  resource: "@ZcoFileBundle/Resources/config/routing/index.yml"

zco_options:
  resource: "@ZcoOptionsBundle/Resources/config/routing.yml"

zco_pages:
  resource: "@ZcoPagesBundle/Resources/config/routing.yml"

zco_parser:
  resource: "@ZcoParserBundle/Resources/config/routing.yml"

zco_quiz:
  resource: "@ZcoQuizBundle/Resources/config/routing.yml"

zco_search:
  resource: "@ZcoSearchBundle/Resources/config/routing.yml"

zco_stats:
  resource: "@ZcoStatsBundle/Resources/config/routing.yml"

zco_user:
  resource: "@ZcoUserBundle/Resources/config/routing/index.yml"

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"