zco_user_admin_validateAccount:
    path:   /valider/{id}
    defaults:  { _controller: ZcoUserBundle:Admin:validateAccount, status: true }
    requirements:
        id: \d+

zco_user_admin_unvalidateAccount:
    path:   /devalider/{id}
    defaults:  { _controller: ZcoUserBundle:Admin:validateAccount, status: false }
    requirements:
        id: \d+

zco_user_admin_deleteAccount:
    path:   /supprimer/{id}
    defaults:  { _controller: ZcoUserBundle:Admin:deleteAccount }
    requirements:
        id: \d+

zco_user_admin_punish:
    path:   /sanctionner/{id}
    defaults:  { _controller: ZcoUserBundle:Admin:punish, id: ~ }
    requirements:
        id: \d+

zco_user_admin_cancelPunishment:
    path:   /sanctionner/annuler/{id}
    defaults:  { _controller: ZcoUserBundle:Admin:cancelPunishment }
    requirements:
        id: \d+

zco_user_admin_blocages:
    path:   /blocages
    defaults:  { _controller: ZcoUserBundle:Admin:blocages }

zco_user_admin_searchEmail:
    path:   /rechercher-email
    defaults:  { _controller: ZcoUserBundle:Admin:searchEmail }

zco_user_admin_unvalidAccounts:
    path:   /comptes-non-valides
    defaults:  { _controller: ZcoUserBundle:Admin:unvalidAccounts }

zco_user_admin_bannedEmails:
    path:   /courriels-bannis
    defaults:  { _controller: ZcoUserBundle:Admin:bannedEmails }

zco_user_admin_newBannedEmail:
    path:   /courriels-bannis/nouveau
    defaults:  { _controller: ZcoUserBundle:Admin:newBannedEmail }

zco_user_admin_deleteBannedEmail:
    path:   /courriels-bannis/supprimer/{id}
    defaults:  { _controller: ZcoUserBundle:Admin:bannedEmails }

zco_user_admin_newPseudoQueries:
    path:   /nouveau-pseudo/en-attente
    defaults:  { _controller: ZcoUserBundle:Admin:newPseudoQueries }

zco_user_admin_newPseudoAnswer:
    path:   /nouveau-pseudo/repondre/{id}
    defaults:  { _controller: ZcoUserBundle:Admin:newPseudoAnswer }
    requirements:
        id: \d+