zco_user_index:
    path:   /
    defaults:  { _controller: ZcoUserBundle:Default:index, page: 1 }

zco_user_indexWithPage:
    path:   /{page}
    defaults:  { _controller: ZcoUserBundle:Default:index, page: 1 }
    requirements:
        page: \d+

zco_user_profile:
    path:   /{id}/{slug}
    defaults:  { _controller: ZcoUserBundle:Default:profile }
    requirements:
        id: \d+
        slug: '[a-z0-9-]+'

zco_user_editTitle:
    path:   /modifier-titre/{id}
    defaults:  { _controller: ZcoUserBundle:Default:editTitle }
    requirements:
        page: \d+

zco_user_newPseudo:
    path:   /nouveau-pseudo/{id}
    defaults:  { _controller: ZcoUserBundle:Default:newPseudo, id: ~ }
    requirements:
        id: \d+

zco_user_zformBackups:
    path:   /sauvegardes-zform/{textarea}
    defaults:  { _controller: ZcoUserBundle:Default:zformBackups, textarea: ~ }
    options:   { expose: true }