services:
  zco_stats.event_listener:
    class: Zco\Bundle\StatsBundle\EventListener\EventListener
    arguments: ['@router', '@zco_stats.alexa_stats']
    tags:
      - { name: kernel.event_subscriber }

  zco_stats.alexa_stats:
    class: Zco\Bundle\StatsBundle\Service\AlexaStatsService
    arguments: ['@zco_doctrine1.connection']

  zco_stats.user_stats:
      class: Zco\Bundle\StatsBundle\Service\UserStatsService
      arguments: ['@zco_doctrine1.connection']

  zco_stats.forum_stats:
      class: Zco\Bundle\StatsBundle\Service\ForumStatsService
      arguments: ['@zco_doctrine1.connection', '@zco_core.cache']

  zco_stats.alexa_chart:
    class: Zco\Bundle\StatsBundle\Service\AlexaChartService
    arguments: ['@zco_stats.alexa_stats']

  zco_stats.location_chart:
      class: Zco\Bundle\StatsBundle\Service\LocationChartService
      arguments: ['@zco_stats.user_stats']

  zco_stats.registration_chart:
        class: Zco\Bundle\StatsBundle\Service\RegistrationChartService
        arguments: ['@zco_stats.user_stats']

  zco_stats.ages_chart:
        class: Zco\Bundle\StatsBundle\Service\AgesChartService
        arguments: ['@zco_stats.user_stats']