zco_content_tag:
  path:   /tags/{id}/{slug}
  defaults:  { _controller: ZcoContentBundle:Tags:view, slug: ~ }
  requirements:
    id: \d+

zco_quote_index:
  path:   /citations
  defaults:  { _controller: ZcoContentBundle:Quotes:index }

zco_quote_new:
  path:   /citations/ajouter
  defaults:  { _controller: ZcoContentBundle:Quotes:new }

zco_quote_edit:
  path:   /citations/modifier/{id}
  defaults:  { _controller: ZcoContentBundle:Quotes:edit }
  requirements:
    id: \d+

zco_quote_delete:
  path:   /citations/supprimer/{id}
  defaults:  { _controller: ZcoContentBundle:Quotes:delete }
  requirements:
    id: \d+
