zco_quote_index:
  path:   /citations
  defaults:  { _controller: ZcoContentBundle:Quotes:index }

zco_quote_new:
  path:   /citations/ajouter
  defaults:  { _controller: ZcoContentBundle:Quotes:new }

zco_quote_edit:
  path:   /citations/modifier/{id}
  defaults:  { _controller: ZcoContentBundle:Quotes:edit }
  requirements:
    id: \d+

zco_quote_delete:
  path:   /citations/supprimer/{id}
  defaults:  { _controller: ZcoContentBundle:Quotes:delete }
  requirements:
    id: \d+

zco_categories_index:
  path:   /categories
  defaults:  { _controller: ZcoContentBundle:Category:index }

zco_categories_new:
  path:   /categories/ajouter
  defaults:  { _controller: ZcoContentBundle:Category:new }

zco_categories_edit:
  path:   /categories/modifier/{id}
  defaults:  { _controller: ZcoContentBundle:Category:edit }
  requirements:
    id: \d+

zco_categories_delete:
  path:   /categories/supprimer/{id}
  defaults:  { _controller: ZcoContentBundle:Category:delete }
  requirements:
    id: \d+

zco_search_index:
  path:      /recherche
  defaults:  { _controller: ZcoContentBundle:Search:index }
