services:
  zco_quiz.event_listener:
    class: Zco\Bundle\QuizBundle\EventListener\EventListener
    arguments: ['@router', '@zco_quiz.manager.quiz']
    tags:
      - { name: kernel.event_subscriber }

  zco_quiz.stats:
    class: Zco\Bundle\QuizBundle\Service\StatsService

  zco_quiz.manager.quiz:
      class: Zco\Bundle\QuizBundle\Entity\QuizManager
      arguments: ['@zco_doctrine1.connection', '@cache']

  zco_quiz.manager.score:
        class: Zco\Bundle\QuizBundle\Entity\QuizScoreManager
        arguments: ['@zco_doctrine1.connection']